# Generated by Django 3.2.25 on 2024-12-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='Pin',
        ),
    ]
