# Generated by Django 3.2.25 on 2024-12-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_table_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='Image',
            field=models.CharField(max_length=100),
        ),
    ]
