# Generated by Django 3.2.25 on 2024-12-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='Image',
            field=models.FileField(upload_to=''),
        ),
    ]
