

from django.contrib import admin
from django.urls import path,include
from app import views

urlpatterns = [
    path('', views.loginpage),
    path('loginpage_post', views.loginpage_post),
    path('admin_add_crop', views.admin_add_crop),
    path('admin_ADD_new_CROPS', views.admin_ADD_new_CROPS),
    path('admin_ADD_new_CROPS_post', views.admin_ADD_new_CROPS_post),
    path('admin_add_crop_search', views.admin_add_crop_search),

    path('admin_add_expert', views.admin_add_expert),
    path('delete_crop/<int:id>', views.delete_crop),
    path('approve_expert/<int:id>', views.approve_expert),
    path('reject_expert/<int:id>', views.reject_expert),
    path('approve_farmer/<int:id>', views.approve_farmer),
    path('reject_farmer/<int:id>', views.reject_farmer),

    path('admin_admin_home', views.admin_admin_home),
    path('admin_manage_expert', views.admin_manage_expert),
    path('admin_manage_expert_search', views.admin_manage_expert_search),
    path('admin_verify_farmer', views.admin_verify_farmer),
    path('admin_verify_farmer_search', views.admin_verify_farmer_search),
    path('feedback', views.feedback),
    path('admin_view_user', views.admin_view_user),
    path('admin_compalint', views.admin_compalint),
    path('admin_send_reply/<int:id>', views.admin_send_reply),
    path('farmer_view_soil', views.farmer_view_soil),
    path('admin_send_reply_post', views.admin_send_reply_post),
    path('expert_add_fertilizer', views. expert_add_fertilizer),
    path('expert_add_tips', views.expert_add_tips),
    path('expert_add_tips_post', views.expert_add_tips_post),
    path('expert_doubt', views.expert_doubt),
    path('expert_manage_fertilizer', views.expert_manage_fertilizer),
    path('expert_manage_tips', views.expert_manage_tips),
    path('expert_notification', views.expert_notification),
    path('expert_send_reply/<int:id>', views.expert_send_reply),
    path('expert_send_reply_post', views.expert_send_reply_post),
    path('expert_tips', views.expert_tips),
    path('view_tips', views.view_tips),
    path('expert_tips', views.expert_tips),
    path('farmer_add_product', views.farmer_add_product),
    path('farmer_manage_product_search', views.farmer_manage_product_search),
    path('farmer_add_crop', views.farmer_add_crop),
    path('farmer_ask_doubt', views.farmer_ask_doubt),
    path('farmer_farmer_home', views.farmer_farmer_home),
    path('farmer_farmer_register', views.farmer_farmer_register),
    path('farmer_manage_product', views.farmer_manage_product),
    path('farmer_send_doubt_and_snd_reply', views.farmer_send_doubt_and_snd_reply),
    path('Farmer_notification', views.Farmer_notification),
    path('farmer_view_order_more/<id>', views.farmer_view_order_more),
    path('farmer_view_order', views.farmer_view_order),
    path('farmer_view_tips', views.farmer_view_tips),
    path('farmer_send_complaint', views.farmer_send_complaint),
    path('farmer_send_complaints', views.farmer_send_complaints),
    path('farmer_complaint', views.farmer_complaint),
    path('farmer_complaint_search', views.farmer_complaint_search),
    path('delete_product/<int:id>', views.delete_product),
    path('farmer_view_fertilizer', views.farmer_view_fertilizer),
    path('sendfeedback', views.sendfeedback),
    path('feedback', views.feedback),
    path('sendfeedback_post', views.sendfeedback_post),



    path('admin_add_expert_post', views.admin_add_expert_post),
    path('expert_delete_tips/<id>', views.expert_delete_tips),
    path('expert_add_fertilizer_post', views.expert_add_fertilizer_post),
    path('delete_fertilizer/<id>', views.delete_fertilizer),
    path('expert_edit_fertilizer/<id>', views.expert_edit_fertilizer),
    path('expert_edit_fertilizer_post', views.expert_edit_fertilizer_post),
    path('expert_manage_soil', views.expert_manage_soil),
    path('expert_add_soil', views.expert_add_soil),
    path('admin_add_notification', views.admin_add_notification),
    path('expert_add_soil_post', views.expert_add_soil_post),
    path('expert_edit_soil_post', views.expert_edit_soil_post),
    path('expert_edit_soil/<int:id>', views.expert_edit_soil),
    path('delete_soil/<id>', views.delete_soil),
    path('farmer_send_compaliant_post', views.farmer_send_compaliant_post),
    path('farmer_add_product_post', views.farmer_add_product_post),
    path('farmer_edit_product_post', views.farmer_edit_product_post),
    path('farmer_edit_product/<int:id>', views.farmer_edit_product),
    path('farmer_send_doubt_post', views.farmer_send_doubt_post),
    path('farmer_ask_doubt_post', views.farmer_ask_doubt_post),
    path('approve_order/<id>', views.approve_order),
    path('reject_order/<id>', views.reject_order),
    path('farmer_doubt_search', views.farmer_doubt_search),
    path('MANAGENOTIFICATION', views.MANAGENOTIFICATION),
    path('delete_notification/<id>', views.delete_notification),
    path('admin_add_notfication', views.admin_add_notification),
    path('admin_add_notification_post', views.admin_add_notification_post),
    path('farmer_farmer_register_post', views.farmer_farmer_register_post),
    path('forgot_password', views.forgot_password),
    path('frget', views.frget),
    path('leaf_prediction', views.leaf_prediction),
    path('leaf_prediction_post', views.leaf_prediction_post),
    path('crop_prediction', views.crop_prediction),
    path('crop_prediction_post', views.crop_prediction_post),
    path('farmer_notification', views.farmer_notification),
    path('logout', views.logout),



    path('logincode', views.logincode),
    path('viewnotification', views.viewnotification),
    path('AppComplaint', views.AppComplaint),
    path('viewreply', views.viewreply),
    path('viewproduct', views.viewproduct),
    path('viewproductmore', views.viewproductmore),
    path('orderscode', views.orderscode),
    path('Androidregistration', views.Androidregistration),
    path('viewprofile', views.viewprofile),
    path('user_edit_profile', views.user_edit_profile),
    path('userpayment', views.userpayment),
    path('/DeleteMyComplaint', views.DeleteMyComplaint),
    # path('home', views.home),
    # path('weather', views.weather),






]
